# Generated by Django 4.0.6 on 2022-07-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='chief',
        ),
    ]
