# Generated by Django 4.0.6 on 2022-07-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_employee_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.employee'),
        ),
    ]
