# Generated by Django 4.0.6 on 2022-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_employee_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
